"""empty message

Revision ID: a8a497503bb1
Revises: 874beb176649
Create Date: 2023-09-27 17:34:47.947461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a497503bb1'
down_revision = '874beb176649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_movies')
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=500), nullable=False))
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=120),
               nullable=True)

    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_id', sa.Integer(), nullable=False))
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_constraint('watchlist_created_at_key', type_='unique')
        batch_op.drop_constraint('watchlist_title_key', type_='unique')
        batch_op.create_foreign_key(None, 'movies', ['movie_id'], ['id'])
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('watchlist_title_key', ['title'])
        batch_op.create_unique_constraint('watchlist_created_at_key', ['created_at'])
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('movie_id')

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('image')

    op.create_table('watchlist_movies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('watchlist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='watchlist_movies_movie_id_fkey'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.id'], name='watchlist_movies_watchlist_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='watchlist_movies_pkey')
    )
    # ### end Alembic commands ###
